name: Train LSTM Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install pip
        run: |
          apt-get update && apt-get install -y python3-pip

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install matplotlib

      - name: Train LSTM Model
        run: |
          python train.py

      - name: Upload Predictions Plot
        uses: actions/upload-artifact@v2
        with:
          name: predicciones
          path: predicciones.png
