name: Train LSTM Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pip
        run: |
          curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
          python get-pip.py

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install matplotlib 
      - name: Train LSTM Model
        run: |
          python train.py

      - name: Upload Predictions Plot
        uses: actions/upload-artifact@v2
        with:
          name: predicciones
          path: predicciones.png

