name: Train and Evaluate LSTM Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest
    container:
      image: tensorflow/tensorflow:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train LSTM model
        run: |
          python train.py  # Este es el script que contiene el c칩digo para entrenar el modelo LSTM

      - name: Evaluate model and generate plots
        run: |
          python evaluate_model.py  # Este es el script que contiene el c칩digo para evaluar el modelo y generar gr치ficos
          cp predicciones.png path/to/plots/predicciones.png
          cp loss_plot.png path/to/plots/loss_plot.png

      - name: Upload plots
        uses: actions/upload-artifact@v2
        with:
          name: model-plots
          path: path/to/plots  # Ruta donde se generan los gr치ficos (por ejemplo, 'plots/' o 'images/')

      - name: Comment on pull request
        run: |
          echo "Model trained successfully!"
          echo "Metrics:"
          echo "- Validation loss: $loss"
          echo "- MAE: $mae"
          echo "- MSE: $mse"
          echo "- R-squared: $r2"
          echo ""
          echo "![Predicciones del modelo LSTM](path/to/plots/predicciones.png)"
          echo "![Loss vs Training Epoch](path/to/plots/loss_plot.png)"

