name: Train LSTM Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew and Python
        run: |
          # Instala Homebrew si no está instalado
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          # Agrega Homebrew al PATH
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          # Instala Python usando Homebrew
          brew install python

      - name: Install pip
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install matplotlib

      - name: Train LSTM Model
        run: |
          python3 train.py

      - name: Upload Predictions Plot
        uses: actions/upload-artifact@v2
        with:
          name: predicciones
          path: predicciones.png
