
name: Train LSTM Model

on:
  push:
    branches:
      - main  # Define la rama en la que se debe activar el flujo

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train LSTM Model
        run: |
          python train.py

      - name: Generate Predictions Plot
        run: |
          # Run the script to generate predictions and save plot.png
          python generate_predictions.py

      - name: Upload Predictions Plot
        uses: actions/upload-artifact@v2
        with:
          name: predictions
          path: plot.png  # Ruta donde se encuentra el archivo de predicciones generado

